@server = https://samseijuro-cautious-space-xylophone-jxp6jvp47rqhprg-8080.preview.app.github.dev/

####
GET {{server}}


####
GET {{server}}/cursos


####
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Algoritmos", "creditos": 3}


####
